site_name: Enterprise Code Training
site_url: https://your-username.github.io/your-repo-name
repo_url: https://github.com/your-username/your-repo-name

nav:
  - Home: index.md
  - Module 1:
      - Introduction: module-1/intro.md
      - JavaScript Exercise: module-1/javascript.md
      - REST API Practice: module-1/rest.md
      - JRuby Practice: module-1/jruby.md
  - Quizzes:
      - Module 1 Quiz: quizzes/module-1-quiz.md
  - LiaScript Demos:
      - JS via LiaScript: liascript/js.md
      - REST via LiaScript: liascript/rest.md
      - JRuby Workaround: liascript/jruby.md
  - About: about.md

theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
  palette:
    scheme: default

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
